test: &test
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          curl -Ls -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash miniconda.sh -b -p $HOME/miniconda
          $HOME/miniconda/bin/conda create -n slumba -y -c conda-forge python="$PYTHON" numba
          echo 'export PATH=$HOME/miniconda/bin:$PATH' >> $BASH_ENV
          echo 'source activate slumba' >> $BASH_ENV
    - run:
        name: Install slumba
        command: |
          pip install -r requirements_dev.txt
          python setup.py develop
    - run:
        name: Make test reports directory
        command: mkdir -p /tmp/slumba/test-reports/pytest
    - run:
        name: Execute Pytest
        command: |
          pytest -rsxX \
            --doctest-modules \
            --doctest-ignore-import-errors \
            --junitxml=/tmp/test-reports/pytest/junit.xml
    - store_test_results:
        path: /tmp/slumba/test-reports
    - store_artifacts:
        path: /tmp/slumba/test-reports

jobs:
  python27_test:
    docker:
      - image: circleci/python:3.6
    <<: *test
    environment:
      PYTHON: 2.7

  python35_test:
    docker:
      - image: circleci/python:3.6
    <<: *test
    environment:
      PYTHON: 3.5

  python36_test:
    docker:
      - image: circleci/python:3.6
    <<: *test
    environment:
      PYTHON: 3.6

workflows:
  version: 2
  test:
    jobs:
      - python27_test
      - python35_test
      - python36_test
